hlo/models/__init__.py
__all__ = [
    "Attachment",
    "Category",
    "Order",
    "OrderItem",
    "OrderItemMeta",
    "Project",
    "Shop",
    "StockItem",
    "Storage",
    "OrderStockItemLink",
    "User",
    "get_object_from_sha1",
]
import contextlib
import logging

from django.contrib.auth.models import AbstractUser

from .attachment import Attachment
from .commontree import Category, Project, Storage
from .order import Order
from .orderitem import OrderItem, OrderItemMeta
from .orderstockitemlink import OrderStockItemLink
from .shop import Shop
from .stockitem import StockItem

logger = logging.getLogger(__name__)


class User(AbstractUser):
    pass


def get_object_from_sha1(
    sha1: str,
) -> tuple[OrderItem | StockItem | Storage | None, type | None]:
    """Return object and type based on SHA1."""
    sha1 = sha1.upper()
    obj: Storage | StockItem | OrderItem
    with contextlib.suppress(Storage.DoesNotExist):
        obj = Storage.objects.get(sha1_id=sha1)
        return obj, Storage
    with contextlib.suppress(StockItem.DoesNotExist):
        obj = StockItem.objects.get(sha1_id=sha1)
        return obj, StockItem
    with contextlib.suppress(OrderItem.DoesNotExist):
        obj = OrderItem.objects.get(sha1_id=sha1)
        return obj, OrderItem
    logger.debug("SHA1 did not match anything: %s", sha1)
    return None, None

hlo/models/attachment.py
import hashlib
import logging
from pathlib import Path

from django.contrib import admin
from django.core.cache import cache
from django.db import models
from django.urls import reverse
from django.utils.html import format_html

from hlo.utils.overwritingfilestorage import OverwritingFileSystemStorage

logger = logging.getLogger(__name__)


def attachment_file_path(instance, filename):
    if len(instance.sha1) != 40:  # noqa: PLR2004
        msg = f"SHA1 sum is not 40 chars: {instance.sha1}"
        raise ValueError(msg)
    suffix = Path(filename).suffix
    prefix = instance.sha1[:2]
    filename = instance.sha1[2:]
    return f"attachments/hashed/{prefix}/{filename}{suffix}"


class Attachment(models.Model):
    DEFAULT_ATTACHMENT_TYPE = "other"
    ATTACHMENT_TYPE_CHOICES = [
        ("datasheet", "Datasheet"),
        ("scrape", "Scraped page"),
        ("thumbnail", "Thumbnail"),
        ("other", "Other"),
    ]
    name = models.CharField(max_length=255, blank=True, default="")
    comment = models.CharField(max_length=255, blank=True, default="")
    type = models.CharField(
        max_length=50,
        choices=ATTACHMENT_TYPE_CHOICES,
        default=DEFAULT_ATTACHMENT_TYPE,
    )
    text = models.TextField(blank="", default="")

    # https://docs.djangoproject.com/en/3.2/ref/models/fields/#filefield
    file = models.FileField(
        upload_to=attachment_file_path,
        storage=OverwritingFileSystemStorage(),
        max_length=255,
        blank=True,
    )

    sha1 = models.CharField(max_length=40, editable=True)

    manual_input = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name} ({self.type}) ({Path(self.file.name).name})"

    def save(self, *args, **kwargs):
        # pylint: disable=no-member
        if self.file:
            with self.file.open("rb") as f:
                sha1hash = hashlib.sha1()  # noqa: S324
                if f.multiple_chunks():
                    for chunk in f.chunks():
                        sha1hash.update(chunk)
                else:
                    sha1hash.update(f.read())
                self.sha1 = sha1hash.hexdigest()
                logger.debug("Attachment SHA1 was %s", self.sha1)
                super().save(*args, **kwargs)
        else:
            self.sha1 = self.sha1 if self.sha1 else None
        super().save(*args, **kwargs)

    def clear_attachment_caches(self):
        """Update cache keys that depend on StockItems."""
        cache.delete_many(
            [
                "attachment_count",
                "attachment_pdf",
                "attachment_html",
            ],
        )

    def text_or_not(self):
        if len(self.text):
            return "There is text"
        return "There is no text"

    def file_name(self):
        if not self.file:
            return ""
        return Path(self.file.name).name

    def get_parent(self):
        # pylint: disable=no-member
        if self.order.count():
            return self.order.first()
        return self.orderitem.first()

    @admin.display(description="Manual input")
    def text_manual_input(self) -> str:
        return "Yes" if self.manual_input else "No"

    def used_by(self):
        # pylint: disable=no-member
        if self.order.count():
            order = self.order.first()
            return format_html(
                '<a href="{}">{} ({})</a>',
                reverse(
                    "admin:hlo_order_change",
                    args=(order.id,),
                ),
                order.order_id,
                order.shop.branch_name,
            )
        orderitem = self.orderitem.first()
        return format_html(
            '<a href="{}">{}</a>',
            reverse(
                "admin:hlo_orderitem_change",
                args=(orderitem.id,),
            ),
            orderitem.name,
        )

hlo/models/orderstockitemlink.py
from django.db import models
from django.db.models import UniqueConstraint


class OrderStockItemLink(models.Model):
    orderitem_link = models.ForeignKey(
        "OrderItem",
        to_field="sha1_id",
        # When OrderItem is deleted, do nothing
        on_delete=models.DO_NOTHING,
        db_constraint=False,
    )

    stockitem_link = models.ForeignKey(
        "StockItem",
        # When StockItem is deleted, delete link
        on_delete=models.CASCADE,
    )

    class Meta:
        constraints = [
            UniqueConstraint(
                fields=["orderitem_link", "stockitem_link"],
                name="unique_orderitem_stockitem",
            ),
        ]

    def __str__(self):
        return (
            # pylint: disable=no-member
            str(
                f"\nOrderitem: {self.orderitem_link.name}\n"
                f"Stockitem: {self.stockitem_link.name}",
            )
        )

hlo/models/shop.py
from django.contrib import admin
from django.db import models
from django.urls import reverse
from django.utils.html import format_html

from hlo.utils.overwritingfilestorage import OverwritingFileSystemStorage


class Shop(models.Model):  # type: ignore[django-manager-missing]
    name = models.CharField(
        max_length=255,
        help_text=(
            "The name primary shop, Amazon, Distrelec, Adafruit, Kjell.com ..."
        ),
    )
    branch_name = models.CharField(
        max_length=255,
        help_text=(
            "The branch of the primary shop, i.e. Amazon.de"
            " for Amazon, or elfadistrelec.no for Distrelec."
            " default is same as shop name"
        ),
        blank=True,
    )
    icon: models.ImageField = models.ImageField(
        upload_to="shop/icons",
        storage=OverwritingFileSystemStorage(),
        blank=True,
    )

    order_url_template = models.CharField(
        max_length=250,
        help_text="The placeholder {order_id} can be used.",
        blank=True,
    )

    item_url_template = models.CharField(
        max_length=250,
        help_text="The placeholders {order_id} and {item_id} can be used.",
        blank=True,
    )

    manual_input = models.BooleanField(default=True)

    class Meta:
        ordering = ["name"]
        constraints = [
            models.UniqueConstraint(
                fields=["name", "branch_name"],
                name="unique_shop_name_branch_name",
            ),
        ]

    def __str__(self):
        # pylint: disable=no-member
        return f"{self.branch_name.capitalize()}"

    def save(self, *args, **kwargs):
        if not self.branch_name:
            self.branch_name = self.name
        super().save(*args, **kwargs)

    def get_absolute_url(self) -> str:
        return reverse("shop-detail", kwargs={"pk": self.pk})

    def longname(self):
        # pylint: disable=no-member
        return f"{self.branch_name.capitalize()}" + (
            f", a branch of {self.name}"
            if self.name != self.branch_name
            else ""
        )

    @admin.display(description="Manual input")
    def text_manual_input(self) -> str:
        return "Yes" if self.manual_input else "No"

    @admin.display(description="Shop")
    def list_icon(self):
        if self.icon:
            return format_html(
                # pylint: disable=no-member
                f'<img src="{self.icon.url}" width="25"'
                f" />&nbsp;{self.longname()}",
            )
        return f"{self.longname()}"

    def img_icon(self):
        if self.icon:
            return format_html(
                # pylint: disable=no-member
                f'<img src="{self.icon.url}" style="min-height: 2em; min-width:'
                ' 1em; max-height: 2em;">',
            )
        return f"{self.longname()[0]}"

    @admin.display(description="Orders")
    def order_list(self):
        num_orders = self.orders.count()
        if not num_orders:
            return "No orders in database."
        return num_orders

hlo/forms/__init__.py
from .attachment import (
    AttachmentForm,
    AttachmentFormSet,
    AttachmentFormSetHelper,
)
from .order import OrderForm, OrderFormSimple
from .orderitem import OrderItemForm
from .shop import ShopForm
from .stockitem import StockItemForm

__all__ = [
    "StockItemForm",
    "OrderForm",
    "OrderFormSimple",
    "ShopForm",
    "OrderItemForm",
    "AttachmentForm",
    "AttachmentFormSet",
    "AttachmentFormSetHelper",
]

hlo/forms/attachment.py
import logging

from crispy_forms.helper import FormHelper  # type: ignore[import-untyped]
from crispy_forms.layout import (  # type: ignore[import-untyped]
    Column,
    Field,
    Row,
)
from django.forms import ModelForm, modelformset_factory

from hlo.models import Attachment

logger = logging.getLogger(__name__)


class AttachmentForm(ModelForm):
    class Meta:
        model = Attachment
        exclude = ["comment", "text", "manual_input", "sha1"]  # noqa: DJ006


AttachmentFormSet = modelformset_factory(
    model=Attachment,
    form=AttachmentForm,
    extra=1,
)


class AttachmentFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.form_method = "POST"
        self.form_class = "form-vertical"
        self.label_class = "col"
        self.field_class = "col"
        self.render_required_fields = True
        self.form_tag = False
        self.add_layout(
            Column(
                Row(
                    Column(Field("name")),
                    Column(
                        Field("type"),
                    ),
                    Column(Field("file")),
                ),
            ),
        )

hlo/forms/order.py
import logging

from crispy_forms.bootstrap import (  # type: ignore[import-untyped]
    FieldWithButtons,
)
from crispy_forms.helper import FormHelper  # type: ignore[import-untyped]
from crispy_forms.layout import (  # type: ignore[import-untyped]
    Column,
    Field,
    Row,
)
from django.forms import ModelForm
from django.forms.widgets import DateInput, HiddenInput

from hlo.models import Order

logger = logging.getLogger(__name__)


class RealDateInput(DateInput):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.input_type = "date"


class OrderFormSimple(ModelForm):
    class Meta:
        model = Order
        exclude = ["manual_input", "extra_data", "attachments"]  # noqa: DJ006
        widgets = {
            "shop": HiddenInput(),
            "date": RealDateInput(),
        }
        labels = {
            "order_id": "ID",
            "date": "Date",
        }
        help_texts = {
            "order_id": None,
        }

    def __init__(self, *args, **kwargs):
        # We need this so self.fields is populated
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.form_class = "form-vertical"
        self.helper.label_class = "col"
        self.helper.field_class = "col"
        self.helper.form_tag = False
        # self.helper.add_input(Submit("submit", "Create"))

        self.helper.add_layout(
            Column(
                Row(
                    Column(Field("order_id")),
                    Column(
                        Field("date"),
                    ),
                    Column(FieldWithButtons("total")),
                ),
            ),
        )


# Create the form class.
class OrderForm(ModelForm):
    class Meta:
        model = Order
        exclude = ["manual_input"]  # noqa: DJ006

    def __init__(self, *args, **kwargs):
        # We need this so self.fields is populated
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-2"
        self.helper.field_class = "col-10"

hlo/forms/orderitem.py
import logging

from crispy_forms.helper import FormHelper  # type: ignore[import-untyped]
from django.forms import ModelForm

from hlo.models import OrderItem

logger = logging.getLogger(__name__)


class OrderItemForm(ModelForm):
    class Meta:
        model = OrderItem
        exclude = ["manual_input", "sha1_id"]  # noqa: DJ006

    def __init__(self, *args, **kwargs):
        # We need this so self.fields is populated
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-2"
        self.helper.field_class = "col-10"

hlo/forms/shop.py
from crispy_forms.helper import FormHelper  # type: ignore[import-untyped]
from django.forms import ModelForm

from hlo.models import Shop


class ShopForm(ModelForm):
    class Meta:
        model = Shop
        fields = [
            "name",
            "branch_name",
            "icon",
            "order_url_template",
            "item_url_template",
        ]

    def __init__(self, *args, **kwargs):
        # We need this so self.fields is populated
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-2"
        self.helper.field_class = "col-10"

hlo/admin/__init__.py
import logging

from django.contrib import admin
from django.contrib.auth.admin import UserAdmin

from hlo.models import User

from .attachment import AttachmentAdmin
from .commontree import CategoryAdmin, ProjectAdmin, StorageAdmin
from .order import OrderAdmin
from .orderitem import (
    OrderItemAdmin,
    OrderItemMetaAdmin,
    OrderStockItemLinkAdmin,
)
from .shop import ShopAdmin
from .stockitem import StockItemAdmin

logger = logging.getLogger(__name__)

__all__ = [
    "AttachmentAdmin",
    "CategoryAdmin",
    "CategoryResource",
    "OrderAdmin",
    "OrderItemAdmin",
    "OrderItemMetaAdmin",
    "OrderStockItemLinkAdmin",
    "ProjectAdmin",
    "ShopAdmin",
    "StockItemAdmin",
    "StorageAdmin",
    "User",
]

admin.site.register(User, UserAdmin)

hlo/admin/commontree/__init__.py
from .category import CategoryAdmin
from .project import ProjectAdmin
from .storage import StorageAdmin

__all__ = [
    "CategoryAdmin",
    "ProjectAdmin",
    "StorageAdmin",
]

hlo/filters/__init__.py
__all__ = [
    "OrderItemFilter",
    "StockItemFilter",
    "NonOrderingOrderItemFilter",
    "NonOrderingStockItemFilter",
    "OrderDateRangeFilter",
]
from .orderdaterangefilter import OrderDateRangeFilter
from .orderitemfilter import NonOrderingOrderItemFilter, OrderItemFilter
from .stockitemfilter import NonOrderingStockItemFilter, StockItemFilter

hlo/management/commands/loaders/__init__.py
from .shopmetaloader import ShopMetaLoader
from .shoporderloader import ShopOrderLoader

__all__ = [
    "ShopMetaLoader",
    "ShopOrderLoader",
]

hlo/models/commontree/__init__.py
__all__ = [
    "Category",
    "CommonTreeModel",
    "Project",
    "Storage",
]
from .category import Category
from .commontree import CommonTreeModel
from .project import Project
from .storage import Storage

hlo/templates/order/detail.html
{% extends "common/base.html" %}
{% load django_bootstrap5 %}
{% load bootstrap_icons %}
{% block title %}
    Details for {{ order.shop }} #{{ order.order_id }}
{% endblock title %}
{% block content %}
    <div class="row">
        <div class="row">
            <div class="col-2 pt-3 d-none d-lg-block d-xl-block d-xxl-block">
                {% if shop.icon %}
                    <img height="50" src="{{ shop.icon.url }}" class="pe-3" />
                {% else %}
                    {% md_icon 'image-off' color='grey' size='50px' %}
                {% endif %}
            </div>
            <div class="col-10">
                <h1>
                    {{ order.shop.branch_name }}
                    <a href="{{ order.get_order_url }}"
                       title="View original order details"
                       class="text-body-secondary">#{{ order.order_id }}</a>
                    <a class="btn btn-outline-secondary btn-sm"
                       href="{% url 'order-update' order.id %}"
                       role="button">edit</a>
                    <a class="btn btn-outline-secondary btn-sm"
                       href="{% url 'orderitem-create-order' order.id %}"
                       role="button">add item</a>
                </h1>
                <h6 class="text-body-secondary">{{ order.items.count }} items, {{ order.date }}</h6>
                <h3>Total: {{ order.total }}</h3>
            </div>
        </div>
        <table class="table  table-sm table-bordered table-striped table-hover table-sm">
            <thead>
                <tr>
                    {# djlint:off #}
                        <th scope="col" style="min-width: 6em;"></th>{# djlint:o #}
                        <th scope="col">Name</th>
                        <th scope="col">Count</th>
                        <th scope="col">Subtotal</th>
                        <th scope="col">Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for orderitem in order.items.all %}
                        <tr>
                            <td class="p-2"
                                style="min-height: 12em;
                                       height: 6em;
                                       background-size: contain;
                                       background-repeat: no-repeat;{# djlint:of #}
                    {% if orderitem.thumbnail %}background-image: url({{ orderitem.thumbnail.url }});{% endif %}"></td>{# djlint:on #}
                        <td>
                            <a href="{{ orderitem.get_absolute_url }}">{{ orderitem.name }}</a>
                        </td>
                        <td>{{ orderitem.count }}</td>
                        <td>
                            {% if orderitem.subtotal %}
                                {{ orderitem.subtotal }}
                            {% else %}
                                -
                            {% endif %}
                        </td>
                        <td>{{ orderitem.total }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% for attachment in order.attachments.all %}
            Attachment: <a href="{{ attachment.file.url }}">{{ attachment }}</a>
            <br>
        {% endfor %}
    </div>
{% endblock content %}

hlo/templates/order/form.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load bootstrap_icons %}
{% load widget_tweaks %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock title %}
{% block content %}
    <div class="row">
        <div class="col">
            {% if order %}
                <h1>{{ order.shop.branch_name }} order {{ order.order_id }}</h1>
            {% else %}
                <h1>Create order object</h1>
            {% endif %}
        </div>
    </div>
    {% if order and not order.manual_input %}
        <div class="alert alert-danger" role="alert">
            This is a automatically created shop object. Editing is disabled by default. Press <a href="#" id="enableEdit">here</a> to enable editing.
        </div>
    {% endif %}
    <div class="row">
        <div class="col">{% crispy form form.helper %}</div>
    </div>
{% endblock content %}
{% block bodybottom %}
    <script type="text/javascript">
        $(window).on("load", function() {
            $("#enableEdit").on("click", function() { 
                if(confirm("This is a automatically created shop object.\n\nEditing is disabled by default.\n\nAre you REALLY sure you want to edit this object?")) {
                    document.querySelectorAll('*[disabled="disabled"]').forEach((e) => {e.disabled=""}) 
                }
                
            })
            
        })
    </script>
{% endblock bodybottom %}

hlo/templates/order/formset.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load bootstrap_icons %}
{% load widget_tweaks %}
{% load static %}
{% block title %}
    Create order and items
{% endblock title %}
{% block css %}
    #id_total_1 option{
    }
    #id_total_1{
    }
    #id_total_0 {
    flex-grow: 10;
    }
    #div_id_attachments div {
    width: unset;
    }
{% endblock css %}
{% block content %}
    <div class="row">
        <div class="col">
            {% if order %}
                <h1>{{ order.shop.branch_name }} order {{ order.order_id }}</h1>
            {% else %}
                <h1>Create order object</h1>
            {% endif %}
        </div>
    </div>
    <form method="POST">
        {{ formset.management_form |crispy }}
        {{ form.hidden_fields |crispy }}
        <div class="row">
            <div class="col">{% crispy form form.helper %}</div>
        </div>
        <div class="row border rounded ms-1 me-1 p-1 pb-2">
            <div class="col-10">
                <a class="link-underline link-underline-opacity-0 text-reset"
                   data-bs-toggle="collapse"
                   href="#collapseOrderAttachments"
                   role="button"
                   aria-expanded="false"
                   aria-controls="collapseOrderAttachments">Order attachments{% bs_icon 'caret-down-fill' %}</a>
            </div>
            <div class="col-2">
                <div class="collapse text-end" id="collapseOrderAttachments">
                    <a class="link-underline link-underline-opacity-0 text-reset"
                        id="btn_add_attachment"
                       href="#"
                       role="button">{% bs_icon 'plus' %} add attachment</a>
                </div>
            </div>
        </div>
        <div class="collapse" id="collapseOrderAttachments">
            <div class="row  border rounded m-1 pt-2">
                <div class="row" id="formset-container">
                    <div class="col">{% crispy formset formset_helper %}</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-10"></div>
            <div class="col-2">
                <input type="submit"
                       name="submit"
                       value="Create Order object"
                       class="btn btn-primary"
                       id="submit-id-submit">
            </div>
        </div>
    </form>
{% endblock content %}
{% block bodybottom %}
    <script type="text/javascript">
        var formset_template = `
        {% crispy single_form formset_helper %}
        `;
        formset_template = formset_template.replace(/<input[^>]+name="csrfmiddlewaretoken"[^>]+\/?>/, "")
        total_forms = document.querySelector("#id_form-TOTAL_FORMS");
        total_forms_value = parseInt(total_forms.value)-1;
        $(window).on("load", function() {

            $("#btn_add_attachment").on("click", () => {
                formset_increment_regexp = /((?:id|for)="[^"]+_|name=")([^"]+")/gi
                next_formset = formset_template.replaceAll(
                    formset_increment_regexp,
                    "$1form-"+(++total_forms_value)+"-$2"
                    )
                alert(next_formset);
                var dom_nodes = $($.parseHTML('<div class="row" id="formset-container-' + total_forms_value + '">' + next_formset + "</div>"));
                $("#formset-container").parent().append(dom_nodes);
                total_forms.value = total_forms_value
            })
        })

        /* 
        div id="div_id_file"
        label for="id_file"
        input name="file" id="id_file"
        
        div id="div_id_form-0-file"
        label for="id_form-0-file"
        input type="file" name="form-0-file" id="id_form-0-file"

        name="file"
        name="form-0-file"

        for="id_form-0-file"

        id="div_id_file"
        /(id="[^"]+_)([^"]+")/ {$1}form-X-{$2}
        id="div_id_form-0-file"
        */
    </script>
{% endblock bodybottom %}

hlo/templates/order/list.html
{% extends "common/base.html" %}
{% block title %}
  Orders
{% endblock title %}
{% block content %}
  <h1>Order List</h1>
  {% if object_list %}
    <ul>
      {% for book in object_list %}
        <li>
          <a href="{% url 'order-detail' book.id %}">{{ book }}</a>
          ({{ book.author }})
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no loaded orders.</p>
  {% endif %}
{% endblock content %}