hlo/models/attachment.py
import hashlib
import logging
from pathlib import Path

from django.contrib import admin
from django.core.cache import cache
from django.db import models
from django.urls import reverse
from django.utils.html import format_html

from hlo.utils.overwritingfilestorage import OverwritingFileSystemStorage

logger = logging.getLogger(__name__)


def attachment_file_path(instance, filename):
    if len(instance.sha1) != 40:  # noqa: PLR2004
        msg = f"SHA1 sum is not 40 chars: {instance.sha1}"
        raise ValueError(msg)
    suffix = Path(filename).suffix
    prefix = instance.sha1[:2]
    filename = instance.sha1[2:]
    return f"attachments/hashed/{prefix}/{filename}{suffix}"


class Attachment(models.Model):
    DEFAULT_ATTACHMENT_TYPE = "other"
    ATTACHMENT_TYPE_CHOICES = [
        ("datasheet", "Datasheet"),
        ("scrape", "Scraped page"),
        ("thumbnail", "Thumbnail"),
        ("other", "Other"),
    ]
    name = models.CharField(max_length=255, blank=True, default="")
    comment = models.CharField(max_length=255, blank=True, default="")
    type = models.CharField(
        max_length=50,
        choices=ATTACHMENT_TYPE_CHOICES,
        default=DEFAULT_ATTACHMENT_TYPE,
    )
    text = models.TextField(blank="", default="")

    # https://docs.djangoproject.com/en/3.2/ref/models/fields/#filefield
    file = models.FileField(
        upload_to=attachment_file_path,
        storage=OverwritingFileSystemStorage(),
        max_length=255,
        blank=True,
    )

    sha1 = models.CharField(max_length=40, editable=True)

    manual_input = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name} ({self.type}) ({Path(self.file.name).name})"

    def save(self, *args, **kwargs):
        # pylint: disable=no-member
        if self.file:
            with self.file.open("rb") as f:
                sha1hash = hashlib.sha1()  # noqa: S324
                if f.multiple_chunks():
                    for chunk in f.chunks():
                        sha1hash.update(chunk)
                else:
                    sha1hash.update(f.read())
                self.sha1 = sha1hash.hexdigest()
                logger.debug("Attachment SHA1 was %s", self.sha1)
                super().save(*args, **kwargs)
        else:
            self.sha1 = self.sha1 if self.sha1 else None
        super().save(*args, **kwargs)

    def clear_attachment_caches(self):
        """Update cache keys that depend on StockItems."""
        cache.delete_many(
            [
                "attachment_count",
                "attachment_pdf",
                "attachment_html",
            ],
        )

    def text_or_not(self):
        if len(self.text):
            return "There is text"
        return "There is no text"

    def file_name(self):
        if not self.file:
            return ""
        return Path(self.file.name).name

    def get_parent(self):
        # pylint: disable=no-member
        if self.order.count():
            return self.order.first()
        return self.orderitem.first()

    @admin.display(description="Manual input")
    def text_manual_input(self) -> str:
        return "Yes" if self.manual_input else "No"

    def used_by(self):
        # pylint: disable=no-member
        if self.order.count():
            order = self.order.first()
            return format_html(
                '<a href="{}">{} ({})</a>',
                reverse(
                    "admin:hlo_order_change",
                    args=(order.id,),
                ),
                order.order_id,
                order.shop.branch_name,
            )
        orderitem = self.orderitem.first()
        return format_html(
            '<a href="{}">{}</a>',
            reverse(
                "admin:hlo_orderitem_change",
                args=(orderitem.id,),
            ),
            orderitem.name,
        )

hlo/models/orderitem.py
from __future__ import annotations

import hashlib
import logging
import pprint
from io import BytesIO
from pathlib import Path
from typing import TYPE_CHECKING

from django.contrib import admin
from django.core.cache import cache
from django.core.files.images import ImageFile
from django.db import models
from django.db.models import Case, F, When
from django.urls import reverse
from django.utils.html import escape, format_html
from django.utils.safestring import mark_safe
from djmoney.models.fields import MoneyField

from hlo.utils.overwritingfilestorage import OverwritingFileSystemStorage

from . import Attachment, Order

if TYPE_CHECKING:
    from django.utils.safestring import SafeString

logger = logging.getLogger(__name__)


def thumbnail_path(instance: OrderItem, filename: str) -> str:
    if len(instance.thumbnail_sha1) != 40:  # noqa: PLR2004
        msg = f"SHA1 sum is not 40 chars: {instance.thumbnail_sha1}"
        raise ValueError(msg)
    suffix = Path(filename).suffix
    prefix = instance.thumbnail_sha1[:2]
    filename = instance.thumbnail_sha1[2:]
    return f"thumbnails/hashed/{prefix}/{filename}{suffix}"


class OrderItem(models.Model):  # type: ignore[django-manager-missing]
    # the class declaration line in a class that is the target of a ForeignKey
    # from a model with untyped / dynamically added managers as it happens
    # on the reverse relation
    name = models.CharField(max_length=255)
    item_id = models.CharField(
        "Shop item ID",
        max_length=100,
        default="",
        help_text=(
            "The original item id from the shop. Not to be "
            "confused with the internal database id."
        ),
        blank=False,
    )
    item_variation = models.CharField(
        "Item SKU/variation",
        max_length=255,
        default="",
        help_text="The original item sku.",
        blank=True,
    )
    count = models.PositiveIntegerField("number of items", default=1)
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name="items",
    )
    total = MoneyField(
        "Item price",
        max_digits=19,
        decimal_places=4,
        default_currency=None,
        blank=True,
        null=True,
    )  # type: ignore[reportCallIssue]

    total_nok = models.GeneratedField(
        expression=Case(
            When(total_currency="JPY", then=F("total") * 0.0716),
            When(total_currency="USD", then=F("total") * 11.10),
            When(total_currency="GBP", then=F("total") * 14.02),
            When(total_currency="EUR", then=F("total") * 11.72),
            default=F("total"),
            output_field=models.DecimalField(max_digits=19, decimal_places=4),
        ),
        db_persist=False,
        output_field=models.DecimalField(max_digits=19, decimal_places=4),
    )

    subtotal = MoneyField(
        "Item subtotal",
        max_digits=19,
        decimal_places=4,
        default_currency=None,
        blank=True,
        null=True,
    )  # type: ignore[reportCallIssue]
    tax = MoneyField(
        "Item tax/vat",
        max_digits=19,
        decimal_places=4,
        default_currency=None,
        blank=True,
        null=True,
    )  # type: ignore[reportCallIssue]
    attachments = models.ManyToManyField(
        Attachment,
        related_name="orderitem",
        blank=True,
    )

    thumbnail = models.ImageField(
        upload_to=thumbnail_path,  # type: ignore[reportArgumentType]
        storage=OverwritingFileSystemStorage(),
        blank=True,
    )
    # Extra data that we do not import into model
    extra_data = models.JSONField(default=dict, blank=True)

    thumbnail_sha1 = models.CharField(
        max_length=40,
        editable=False,
        default="",
        blank=True,
    )
    # Weak, *static* FK for StockItem
    sha1_id = models.CharField(
        max_length=40,
        unique=True,
    )

    manual_input = models.BooleanField(default=True)

    class Meta:
        ordering = ["order__date", "name"]
        constraints = [
            models.UniqueConstraint(
                fields=["item_id", "item_variation", "order"],
                name="unique_id_sku_order",
            ),
        ]

    def __str__(self) -> str:
        """Return string representation.

        Includes shop, order and item id, variation and NameError
        """
        return (
            # pylint: disable=no-member
            f"{self.pk}: {self.order.shop.branch_name} "
            f" #{self.order.order_id}#{self.item_id}"
            f"/{self.item_variation if len(self.item_variation) else ''}"
            f": {self.name}"
        )

    def save(self, *args, **kwargs) -> None:
        self.thumbnail_sha1 = ""

        buf = BytesIO()
        if self.thumbnail:
            with self.thumbnail.open("rb") as f:
                thumbnail_hash = hashlib.sha1()  # noqa: S324
                if f.multiple_chunks():
                    for chunk in f.chunks():
                        thumbnail_hash.update(chunk)
                        buf.write(chunk)
                else:
                    data = f.read()
                    thumbnail_hash.update(data)
                    buf.write(data)
                self.thumbnail_sha1 = thumbnail_hash.hexdigest()
            buffer_file = ImageFile(buf)
            self.thumbnail.file = buffer_file

        item_variation = "novariation"
        if len(self.item_variation):
            item_variation = self.item_variation

        orderitem_hash = hashlib.sha1()  # noqa: S324
        orderitem_hash.update(
            (
                f"{self.order.shop.branch_name}-{self.order.order_id}-"
                f"{self.item_id}-{item_variation}"
            ).encode(),  # defaults to utf-8
        )
        self.sha1_id = orderitem_hash.hexdigest().upper()
        super().save(*args, **kwargs)
        self.clear_orderitem_caches()

    def get_absolute_url(self) -> str:
        return reverse("orderitem-detail", kwargs={"pk": self.pk})

    def clear_orderitem_caches(self):
        """Update cache keys that depend on StockItems."""
        cache.delete_many(
            [
                "orderitem_raw_count",
                "orderitem_unprocessed_count",
                "orderitem_processed_count",
                "stockitem_count",
            ],
        )

    def simple_image_tag(
        self,
        max_width: int = 300,
        max_height: int = 300,
        classes=None,
        style="",
    ) -> SafeString:
        if classes is None:
            classes = []
        return mark_safe(  # noqa: S308
            f'<img src="{self.thumbnail.url}" class="{" ".join(classes)}" '
            f'style="max-height: {max_height}px; '
            f'max-width: {max_width}px; {style}"/>',
        )

    @admin.display(description="Preview")
    def admin_image_tag(self) -> SafeString:
        return self.simple_image_tag(300, 300)

    def image_tag(self, px: int = 150, max_width: int = 0) -> SafeString:
        # pylint: disable=no-member
        max_width = (
            min(self.thumbnail.width, max_width)
            if max_width
            else self.thumbnail.width
        )
        if px:
            return mark_safe(  # noqa: S308
                f'<div style="height: {px}px;"><a href="{self.thumbnail.url}"'
                ' target="_blank"><img style="height: auto; width: auto;"'
                f' src="{self.thumbnail.url}" width="{self.thumbnail.width}"'
                f' height="{self.thumbnail.height}" /></a></div>',
            )
        return mark_safe(  # noqa: S308
            f'<img style="max-height: 100%; '
            f'width: { f"{max_width} px" if max_width else "auto" };"'
            f' src="{self.thumbnail.url}" />',
        )

    @admin.display(description="Attachments")
    def attachments_tag(self) -> SafeString | str:
        # pylint: disable=no-member
        if self.attachments.count() == 0:
            return "No attachments"
        html = '<ul style="margin: 0;">'
        for attachment in self.attachments.all():
            html += (
                f'<li><a href="{attachment.file.url}"'
                f' target="_blank">{attachment}</a></li>'
            )
        html += "</ul>"
        return mark_safe(html)  # noqa: S308

    @admin.display(description="Item ID / SKU")
    def item_ref(self) -> str:
        return (
            f"{self.item_id}"
            f"{' / ' if len(self.item_variation) else ''}"
            f"{self.item_variation}"
        )

    @admin.display(description="Manual input")
    def text_manual_input(self) -> str:
        return "Yes" if self.manual_input else "No"

    def get_orderitem_url(self) -> str:
        return self.order.shop.item_url_template.format(item_id=self.item_id)

    @admin.display(description="Order ID")
    def item_url(self) -> SafeString:
        return format_html(
            '{} (<a href="{}" target="_blank">Open item page on {}}</a>)',
            self.order_id,  # type: ignore[reportAttributeAccessIssue]
            # pylint: disable=no-member
            self.shop.order_url_template.format(order_id=self.order_id),  # type: ignore[reportAttributeAccessIssue,attr-defined]
            self.shop.branch_name,  # type: ignore[reportAttributeAccessIssue,attr-defined]
        )

    @admin.display(description="Extra data (indented)")
    def indent_extra_data(self) -> SafeString:
        return format_html(
            "<pre>{}</pre>",
            escape(pprint.PrettyPrinter(indent=2).pformat(self.extra_data)),
        )


class OrderItemMeta(models.Model):
    parent = models.OneToOneField(
        OrderItem,
        to_field="sha1_id",
        on_delete=models.DO_NOTHING,
        db_constraint=False,
        related_name="meta",
    )
    hidden = models.BooleanField(default=False)
    label_printed = models.BooleanField(default=False)
    comment = models.CharField(max_length=255, default="", blank=True)

hlo/forms/__init__.py
from .attachment import (
    AttachmentForm,
    AttachmentFormSet,
    AttachmentFormSetHelper,
)
from .order import OrderForm, OrderFormSimple
from .orderitem import OrderItemForm
from .shop import ShopForm
from .stockitem import StockItemForm

__all__ = [
    "StockItemForm",
    "OrderForm",
    "OrderFormSimple",
    "ShopForm",
    "OrderItemForm",
    "AttachmentForm",
    "AttachmentFormSet",
    "AttachmentFormSetHelper",
]

hlo/forms/attachment.py
import logging

from crispy_forms.helper import FormHelper  # type: ignore[import-untyped]
from crispy_forms.layout import (  # type: ignore[import-untyped]
    Column,
    Field,
    Row,
)
from django.forms import ModelForm, modelformset_factory

from hlo.models import Attachment

logger = logging.getLogger(__name__)


class AttachmentForm(ModelForm):
    class Meta:
        model = Attachment
        exclude = ["comment", "text", "manual_input", "sha1"]  # noqa: DJ006


AttachmentFormSet = modelformset_factory(
    model=Attachment,
    form=AttachmentForm,
    extra=1,
)


class AttachmentFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.form_method = "POST"
        self.form_class = "form-vertical"
        self.label_class = "col"
        self.field_class = "col"
        self.render_required_fields = True
        self.form_tag = False
        self.add_layout(
            Column(
                Row(
                    Column(Field("name")),
                    Column(
                        Field("type"),
                    ),
                    Column(Field("file")),
                ),
            ),
        )

hlo/admin/__init__.py
import logging

from django.contrib import admin
from django.contrib.auth.admin import UserAdmin

from hlo.models import User

from .attachment import AttachmentAdmin
from .commontree import CategoryAdmin, ProjectAdmin, StorageAdmin
from .order import OrderAdmin
from .orderitem import (
    OrderItemAdmin,
    OrderItemMetaAdmin,
    OrderStockItemLinkAdmin,
)
from .shop import ShopAdmin
from .stockitem import StockItemAdmin

logger = logging.getLogger(__name__)

__all__ = [
    "AttachmentAdmin",
    "CategoryAdmin",
    "CategoryResource",
    "OrderAdmin",
    "OrderItemAdmin",
    "OrderItemMetaAdmin",
    "OrderStockItemLinkAdmin",
    "ProjectAdmin",
    "ShopAdmin",
    "StockItemAdmin",
    "StorageAdmin",
    "User",
]

admin.site.register(User, UserAdmin)

hlo/admin/commontree/__init__.py
from .category import CategoryAdmin
from .project import ProjectAdmin
from .storage import StorageAdmin

__all__ = [
    "CategoryAdmin",
    "ProjectAdmin",
    "StorageAdmin",
]

hlo/filters/__init__.py
__all__ = [
    "OrderItemFilter",
    "StockItemFilter",
    "NonOrderingOrderItemFilter",
    "NonOrderingStockItemFilter",
    "OrderDateRangeFilter",
]
from .orderdaterangefilter import OrderDateRangeFilter
from .orderitemfilter import NonOrderingOrderItemFilter, OrderItemFilter
from .stockitemfilter import NonOrderingStockItemFilter, StockItemFilter

hlo/management/commands/loaders/__init__.py
from .shopmetaloader import ShopMetaLoader
from .shoporderloader import ShopOrderLoader

__all__ = [
    "ShopMetaLoader",
    "ShopOrderLoader",
]

hlo/models/commontree/__init__.py
__all__ = [
    "Category",
    "CommonTreeModel",
    "Project",
    "Storage",
]
from .category import Category
from .commontree import CommonTreeModel
from .project import Project
from .storage import Storage

hlo/templates/stockitem/filter.html
{% extends "common/base.html" %}
{% load django_bootstrap5 %}
{% load bootstrap_icons %}
{% load crispy_forms_tags %}
{% block title %}
  Find stock items
{% endblock title %}
{% block css %}
  .table-row{
  cursor:pointer;
  }
  td.thumbnail {
    min-height: 12em;
    height: 6em;
    background-size: contain;
    background-repeat: no-repeat;
    background-position-y: center;
  }
{% endblock css %}
{% block javascript %}
  function trLink() {
    window.document.location = this.dataset.href;
  }
  window.addEventListener("load", () => {
    const preview = document.querySelectorAll(".table-row");
    for (let tr of preview) {
      tr.addEventListener("click", trLink.bind(tr));
    }
  });
{% endblock javascript %}
{% block head %}
<script type="text/javascript">
  function isElementInViewport (el) {
    var rect = el.getBoundingClientRect();
    return (
        rect.top >= 0 &&
        rect.left >= 0 &&
        rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) && /* or $(window).height() */
        rect.right <= (window.innerWidth || document.documentElement.clientWidth) /* or $(window).width() */
    );
  }
  function sxp(path, relative) {
    if (!relative) {
      relative = document.body;
    }
    return document.evaluate(
    path,
    relative,
    null,
    XPathResult.FIRST_ORDERED_NODE_TYPE
    ).singleNodeValue;
  }



  window.addEventListener("load", function($) {
    if (!(new URL(document.location).search)) {
      console.log("calc wis");
      let visible = 0;
      rows = document.querySelectorAll("tr.table-row")
      for (let row of rows) {
        if (isElementInViewport(row)) {
          visible = visible + 1;
        }
      }
      if (rows.length > visible) {
        visible = Math.max(visible-1, 5)
        console.log("New page size", visible);
        document.location = document.location + `?per_page=${visible}`
      }
    } else {
      console.log("not calculating page size");
    }
  });
</script>
{% endblock head %}
{% block modals %}
{% endblock modals %}
{% block content %}
{% include "common/filter_modal.html" %}
  <div class="row pb-3 d-none d-sm-none d-md-none d-lg-block d-xl-block d-xxl-block" id="searchfieldFull">
    <div class="col-12 ">
      <!-- CRISPY FORM START -->
      {% load crispy_forms_tags %}
      {% crispy filter.form %}
      <!-- CRISPY FORM END -->
    </div>
  </div>
  <div class="row">
    <div class="col">
      <table class="table table-sm table-bordered table-striped table-hover table-sm">
        <thead>
          <tr>
            <th scope="col" style="min-width: 6em;"></th>
            <th scope="col">Name</th>
          </tr>
        </thead>
        <tbody>
          {% for stockitem in page_obj %}
            <!-- transform as a hack to stop .stretched-link -->
            <tr class="table-row" data-href="{{ stockitem.get_absolute_url }}">
              {% with thumb_link=stockitem.thumbnail_url %}
                <td class="p-2 thumbnail"
                    style="{% if thumb_link %}background-image: url({{ thumb_link }});
                           {% endif %}"></td>
              {% endwith %}
              <td class="align-middle">
                <a href="{{ stockitem.get_absolute_url }}">{{ stockitem.name }}</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <hr>
  {% include "common/pagination.html" %}
{% endblock content %}

hlo/templates/stockitem/form.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load bootstrap_icons %}
{% load widget_tweaks %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock title %}
{% block head %}
<link rel="stylesheet" href="{% static 'select2-bootstrap-5-theme/select2-bootstrap-5-theme.css' %}" />
 
    <link rel="stylesheet"
          href="{% static 'js/multiselect-dropdown/multiselect-dropdown.css' %}">
    <script src="{% static 'js/select-drop-paste.js' %}"></script>
    <script type="text/javascript">
        window.sdp = new SDP({
            showErrorCallback: showError,
            hideErrorCallback: hideError,
            fileInputElement: "#id_thumbnail",
            dropzoneElement: "#dropzone",
            imageElement: "#thumbnail",
            acceptedMimeTypes: ['image/png', 'image/jpeg'],
            debug: false,
            newFileCallback: previewFile
        });
        function showError(msg) {
            console.log(msg)
        }
        function hideError() {

        }
        function previewFile(file) {
            console.log("Got new file")
            const preview = document.querySelector("#thumbnail");
            preview.classList.remove("d-none");
            const reader = new FileReader();
            reader.addEventListener("load", () => {
                preview.src = reader.result;
            }, false);
            reader.readAsDataURL(file);
        }

        window.addEventListener("load", () => {

            /* jQuery + select2  multiselect dropdowns */
            [
                "attachments",
                "orderitems",
                "storage",
                "category",
                "project"
            ].forEach((i) => {
                $('#id_' + i ).select2({ theme: "bootstrap-5" });
            });

            /* Button to clear any image changes that has happened */
            document.querySelector("#id_thumbnail_btnclear").addEventListener(
                'click', 
                () => { 
                    document.querySelector('#id_thumbnail').value=null;
                    const preview = document.querySelector("#thumbnail");
                    const original_url = "{% if stockitem.thumbnail_url %}{{ stockitem.thumbnail_url }}{% elif orderitem.thumbnail %}{{ orderitem.thumbnail.url }}{% endif %}";
                    if (original_url) {
                        preview.src = original_url;
                    } else {
                        preview.classList.add("d-none");
                    }
                }
                );
            
            /* On screen keyboard buttons*/
            [
                ["diameter","⌀"],
                ["degree","°"]
            ].forEach((inp) => {
                document.querySelector("#btn_" + inp[0]).addEventListener("click", () => {
                    document.querySelector("#id_name").setRangeText(inp[1])
                });
            })

            /* Button for adding new units */
            document.querySelector("#unit_btn").addEventListener("click", () => {
                var v = prompt("New unit")
                if (!v || v.trim() == "") {
                    return
                }
                v = v.trim()
                const o = document.createElement("option");
                o.value = v;
                o.text = v;
                s = document.querySelector("#id_count_unit")
                s.add(o);
                s.value = v;
            });

            document.querySelector("#btn_rotate_90_right").addEventListener("click", () => {
                window.sdp.rotate("right")
            });
            document.querySelector("#btn_rotate_180").addEventListener("click", () => {
                window.sdp.rotate("180")

            });
            document.querySelector("#btn_rotate_90_left").addEventListener("click", () => {
                window.sdp.rotate("left")
            });

        });
    </script>
    <!-- select2-bootstrap5 dark mode overrides -->
    <link href="{% static 'css/select2-bootstrap5-dark.css' %}" media="screen" rel="stylesheet">
{% endblock head %}
{% block modals %}
    <div class="modal" tabindex="-1" id="keyboardModel">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body">
                    <button type="button"
                            class="btn btn-primary"
                            id="btn_diameter"
                            data-bs-dismiss="modal">⌀</button>
                    <button type="button"
                            class="btn btn-primary"
                            id="btn_degree"
                            data-bs-dismiss="modal">°</button>
                </div>
            </div>
        </div>
    </div>
{% endblock modals %}
{% block content %}
    <div class="row mt-2 mb-4">
        <div class="col">
            
            {% if stockitem.name %}
                <h1>{{ stockitem.name }}</h1>
            {% else %}
                <h1>
                    Create stock item
                    <br>
                </h1>
                <h4 class="text-secondary">{{ original_name }}</h4>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col">{% crispy form %}</div>
    </div>
    {% endblock content %}